package com.sandu.xinye.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("about", "aboutId", About.class);
		arp.addMapping("banner", "id", Banner.class);
		arp.addMapping("everyday_data", "id", EverydayData.class);
		arp.addMapping("feedback", "feedbackId", Feedback.class);
		arp.addMapping("font", "fontId", Font.class);
		arp.addMapping("help", "helpId", Help.class);
		arp.addMapping("logo", "logoId", Logo.class);
		arp.addMapping("logo_child_kind", "logoChildKindId", LogoChildKind.class);
		arp.addMapping("logo_kind", "logoKindId", LogoKind.class);
		arp.addMapping("machine", "machineId", Machine.class);
		arp.addMapping("menu", "menuId", Menu.class);
		arp.addMapping("operation_log", "id", OperationLog.class);
		arp.addMapping("sys_role_menu", "sysRoleMenuId", SysRoleMenu.class);
		arp.addMapping("sys_user", "sysUserId", SysUser.class);
		arp.addMapping("sys_user_role", "sysUserRoleId", SysUserRole.class);
		arp.addMapping("sys_user_session", "sessionId", SysUserSession.class);
		arp.addMapping("user", "userId", User.class);
		arp.addMapping("user_session", "sessionId", UserSession.class);
	}
}

