package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseAbout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class About extends BaseAbout<About> {
	public static final About dao = new About().dao();
}
