package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Banner extends BaseBanner<Banner> {
	public static final Banner dao = new Banner().dao();
}
