package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseEverydayData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EverydayData extends BaseEverydayData<EverydayData> {
	public static final EverydayData dao = new EverydayData().dao();
}
