package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseFont;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Font extends BaseFont<Font> {
	public static final Font dao = new Font().dao();
}
