package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseHelp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Help extends BaseHelp<Help> {
	public static final Help dao = new Help().dao();
}
