package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseLogoChildKind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogoChildKind extends BaseLogoChildKind<LogoChildKind> {
	public static final LogoChildKind dao = new LogoChildKind().dao();
}
