package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseLogo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logo extends BaseLogo<Logo> {
	public static final Logo dao = new Logo().dao();
}
