package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseLogoKind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogoKind extends BaseLogoKind<LogoKind> {
	public static final LogoKind dao = new LogoKind().dao();
}
