package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseMachine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Machine extends BaseMachine<Machine> {
	public static final Machine dao = new Machine().dao();
}
