package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu().dao();
	
	public static final int STATUS_OK = 1;
}
