package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseOperationLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperationLog extends BaseOperationLog<OperationLog> {
	public static final OperationLog dao = new OperationLog().dao();
}
