package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseSysUserSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserSession extends BaseSysUserSession<SysUserSession> {
	public static final SysUserSession dao = new SysUserSession().dao();
	
	/**
	 * 登录会话是否已过期
	 */
	public boolean isExpired() {
		return getTimeStamp() < System.currentTimeMillis();
	}
}
