package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	
	/*
	 * 1-已注册   2-已登录  
	 */
	public static final int STATUS_IS_REGISTER = 1;
	public static final int STATUS_IS_LOGINED = 2;
	
	/*
	 * 0-qq注册登录   1-微信注册登录   2-手机注册登录
	 */
	public static final int REGISTER_TYPE_QQ = 0;
	public static final int REGISTER_TYPE_WX = 1;
	public static final int REGISTER_TYPE_PHONE = 2;
	
	/**
	 * @Title: removeSensitiveInfo
	 * @Description:  
	 * @date 2019年3月13日  下午3:14:53
	 * @author  liyingxiang
	 */
	public User removeSensitiveInfo() {
		return this.remove("userPass","salt");
	}
}
