package com.sandu.xinye.common.model;

import com.sandu.xinye.common.model.base.BaseUserSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSession extends BaseUserSession<UserSession> {
	public static final UserSession dao = new UserSession().dao();
	
	/**
	 * 登录会话是否已过期
	 */
	public boolean isExpired() {
		return getTimeStamp() < System.currentTimeMillis();
	}
}
