package com.sandu.xinye.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLogoKind<M extends BaseLogoKind<M>> extends Model<M> implements IBean {

	public M setLogoKindId(java.lang.Integer logoKindId) {
		set("logoKindId", logoKindId);
		return (M)this;
	}
	
	public java.lang.Integer getLogoKindId() {
		return getInt("logoKindId");
	}

	public M setLogoKindName(java.lang.String logoKindName) {
		set("logoKindName", logoKindName);
		return (M)this;
	}
	
	public java.lang.String getLogoKindName() {
		return getStr("logoKindName");
	}

	public M setSysUserId(java.lang.Integer sysUserId) {
		set("sysUserId", sysUserId);
		return (M)this;
	}
	
	public java.lang.Integer getSysUserId() {
		return getInt("sysUserId");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
